#!/bin/sh
#
# @name DJI f450 SITL model for JSBSim
#
# @type Quadrotor
#
# @maintainer Eric Johnson
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.1651
param set-default CA_ROTOR0_PY 0.1651
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.1651
param set-default CA_ROTOR1_PY -0.1651
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.1651
param set-default CA_ROTOR2_PY -0.1651
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.1651
param set-default CA_ROTOR3_PY 0.1651
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default MC_PITCHRATE_P 0.05
param set-default MC_PITCHRATE_I 0.05
param set-default MC_PITCH_P 2
param set-default MC_ROLLRATE_P 0.05
param set-default MC_ROLLRATE_I 0.05
param set-default MC_ROLL_P 2
param set-default MPC_XY_VEL_I_ACC 0.4
param set-default MPC_XY_VEL_P_ACC 1.8
